---
- name: Setup Nginx
  hosts: localhost
  become: true
  tasks:
    - name: Ensure Nginx is installed
      package:
        name: nginx
        state: present

    - name: Stop Nginx service (if running)
      service:
        name: nginx
        state: stopped
        enabled: false
