---
- name: Provision SharpishlyApp environment
  hosts: localhost
  become: true
  tasks:
    # =============================
    # Step 1: Ensure required packages
    # =============================
    - name: Install required packages
      package:
        name:
          - openssl
          - docker.io
          - docker-compose-plugin
          - ufw
        state: present

    # =============================
    # Step 2: Generate self-signed SSL cert
    # =============================
    - name: Ensure certs directory exists
      file:
        path: certs
        state: directory
        owner: "{{ ansible_user }}"
        mode: "0755"

    - name: Generate SSL private key
      community.crypto.openssl_privatekey:
        path: certs/sharpishly.dev.key
        size: 4096

    - name: Generate self-signed certificate
      community.crypto.x509_certificate:
        path: certs/sharpishly.dev.crt
        privatekey_path: certs/sharpishly.dev.key
        provider: selfsigned
        subject:
          common_name: sharpishly.dev
          organization_name: Self-Signed
          country_name: US
          state_or_province_name: California
          locality_name: Mountain View
        days: 365

    # =============================
    # Step 3: Manage docker stack
    # =============================
    - name: Stop any existing containers
      community.docker.docker_compose:
        project_src: .
        state: absent

    - name: Build and start containers
      community.docker.docker_compose:
        project_src: .
        build: true
        state: present
        restarted: true

    # =============================
    # Step 4: Configure firewall
    # =============================
    - name: Allow HTTP and HTTPS through firewall
      ufw:
        rule: allow
        port: "{{ item }}"
      loop:
        - "80"
        - "443"

    - name: Reload firewall
      command: ufw reload

    # =============================
    # Step 5: Update /etc/hosts
    # =============================
    - name: Add hostname entries
      lineinfile:
        path: /etc/hosts
        line: "127.0.0.1 {{ item }}"
        state: present
      loop:
        - sharpishly.dev
        - dev.sharpishly.dev
        - docs.sharpishly.dev
        - live.sharpishly.dev
        - py.sharpishly.dev
