---
- name: Provision SharpishlyApp environment
  hosts: localhost
  become: true

  tasks:
    - name: Ensure base packages
      package:
        name:
          - openssl
          - ufw
        state: present

    - name: Include Docker setup
      import_playbook: docker.yml

    - name: Include SSL setup
      import_playbook: ssl.yml

    - name: Include Nginx setup
      import_playbook: nginx.yml

    - name: Configure firewall
      ufw:
        rule: allow
        port: "{{ item }}"
      loop:
        - "80"
        - "443"

    - name: Reload firewall
      command: ufw reload

    - name: Add hostname entries
      lineinfile:
        path: /etc/hosts
        line: "127.0.0.1 {{ item }}"
        state: present
      loop:
        - sharpishly.dev
        - dev.sharpishly.dev
        - docs.sharpishly.dev
        - live.sharpishly.dev
        - py.sharpishly.dev
