---
- name: Add hostname entries
  lineinfile:
    path: /etc/hosts
    line: "127.0.0.1 {{ item }}"
    state: present
  loop:
    - sharpishly.dev
    - dev.sharpishly.dev
    - docs.sharpishly.dev
    - live.sharpishly.dev
    - py.sharpishly.dev
