---
- name: Deploy SharpishlyApp C++ MVC Framework
  hosts: localhost
  become: yes
  tasks:

    - name: Allow port 1966
      ufw:
        rule: allow
        port: 1966
        proto: tcp

    - name: Ensure UFW is enabled
      ufw:
        state: enabled

    - name: Set permissions for View directory
      file:
        path: "{{ playbook_dir }}/../SharpishlyApp/src/View"
        recurse: yes
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_gid | default(ansible_user_id) }}"
        mode: u+rwX

    - name: Stop Nginx service
      service:
        name: nginx
        state: stopped
      ignore_errors: yes

    - name: Debug www directory contents
      command: ls -l "{{ playbook_dir }}/../SharpishlyApp/src/View/www"
      register: www_list

    - debug:
        var: www_list.stdout_lines

    - name: Create build directory if missing
      file:
        path: "{{ playbook_dir }}/../SharpishlyApp/build"
        state: directory

    - name: Compile SharpishlyApp with CMake
      command: cmake ..
      args:
        chdir: "{{ playbook_dir }}/../SharpishlyApp/build"

    - name: Build SharpishlyApp
      command: make
      args:
        chdir: "{{ playbook_dir }}/../SharpishlyApp/build"

    - name: Run SharpishlyApp
      command: ./SharpishlyApp
      args:
        chdir: "{{ playbook_dir }}/../SharpishlyApp/build"
      async: 30
      poll: 0
      register: app_job

    - debug:
        msg: "SharpishlyApp started in background (Job ID: {{ app_job.ansible_job_id }})"
