name: Deploy to DigitalOcean Droplet

# This workflow runs on a push to the 'main' branch
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Deploy to DigitalOcean Droplet via SSH
      - name: Deploy with SSH and pull latest code
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            # Navigate to the correct directory

            # main branch
            cd ~/Documents/PREDEV/
            
            # Run the deployment commands provided by the user

            # Make safe before pulling new code
            git stash

            # Git pull command by it's self
            git pull origin main

            # Git pull main repository and submodules
            #git submodule update --init --recursive

            # Run application
            ./run.sh







